trigger:
- main

variables:
  tag: '$(Build.BuildId)'
stages:
  - stage: Build
    displayName: Build Stage
    jobs:
    - job: Build
      displayName: Build Job
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'manual-aksdevopsacr-svc'
            repository: 'custom2aksnginxapp1'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: |
              $(tag)
              $(Build.SourceVersion)
        
